ByteProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('events.urls')),
]

events/urls.py
from django.urls import path,re_path, include

from django.contrib.auth import views as auth_views


from . import views

app_name = 'events'

urlpatterns = [
	path('',views.index, name='index'),
	path('login/',views.log_in, name='login'),
    path('logout/',views.log_out, name='logout'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('register/',views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('password/',views.change_password, name='change_password'),
    path('accounts/password_reset/',auth_views.password_reset,name='password_reset'),
    path('accounts/password_reset/done/',auth_views.password_reset_done,name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.password_reset_confirm,name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.password_reset_complete,name='password_reset_complete'),
    path('dashboard/myevents/',views.event_list,name='event_list'),
    path('dashboard/myevents/create/',views.create_event,name='create_event'),
    path('dashboard/myevents/edit/<int:title_id>', views.edit_event,name='edit_event'),
    path('dashboard/myevents/delete/<int:title_id>',views.delete_event,name='delete_event'),
    path('dashboard/attend/<int:title_id>/',views.attendance,name='attendance'),
    path('dashboard/no_attend/<int:title_id>/',views.not_attending,name='not_attending'),
    path('dashboard/events_to_attend/',views.my_events,name='my_events'),
    path('dashboard/events_to_attend/list_of_attendees/<title>/',views.list_of_attendees,name='attendees'),



]

events/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User

import datetime

 


class Schedule(models.Model):
	title = models.CharField(max_length=50)
	day = models.DateField('Date of the Event',help_text="Date")
	start_time = models.TimeField('Time of the Event',help_text="Time")
	venue = models.CharField(max_length=50,null=True)
	notes = models.TextField('Textual Notes',help_text='Textual Notes',blank=True,null=True)
	username = models.ForeignKey(User, on_delete=models.CASCADE)
	attending = models.IntegerField(default=0)
	not_attending = models.IntegerField(default=0)


	def __str__(self):
		return self.title




	class Meta:
		verbose_name = 'Scheduling'
		verbose_name_plural = 'Scheduling'

class Attending(models.Model):
	title = models.CharField(max_length=50,null=True)
	username = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class NotAttending(models.Model):
	title = models.CharField(max_length=50,null=True)
	username = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class EventAttendance(models.Model):
	username = models.ForeignKey(User, on_delete=models.CASCADE)
	event_key = models.ForeignKey(Schedule, on_delete=models.CASCADE)

	def __str__(self):
		return "%s - %s" % (self.event_key, self.username)

events/forms.py
from django import forms
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Schedule
# from .models import SurveyChoice

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    first_name = forms.CharField(max_length=200, help_text='Required')
    last_name = forms.CharField(max_length=200,help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name','password1', 'password2')

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class EventForm(forms.ModelForm):
	class Meta:
		model = Schedule
		fields = ('title','day','start_time','venue','notes',)


class EntryForm(forms.Form):
    name = forms.CharField(max_length=100)
    date = forms.DateTimeField()
    description = forms.CharField(widget=forms.Textarea)

events/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .models import Schedule,Attending,NotAttending,EventAttendance

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import login, authenticate,logout

from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm,SignupForm,EventForm

from django.contrib.auth.models import User

from django.urls import reverse

from django.forms import formset_factory,BaseFormSet

import requests

from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.forms import PasswordChangeForm

from django.conf import settings

from django.contrib import messages

from django.template.loader import render_to_string

from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes, force_text

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .tokens import account_activation_token

from django.core.mail import EmailMessage

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import datetime


from django.views.generic import TemplateView, ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def index(request):
	if request.user.is_authenticated:
		return redirect('events:dashboard')
	

	return render(request, 'events/index.html')

def log_in(request):
    if request.user.is_authenticated:
        return redirect('polls:dashboard')
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
        	recaptcha_response = request.POST.get('g-recaptcha-response')
        	data = {
        		'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
        		'response': recaptcha_response
        	}
        	r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        	result = r.json()
        	print(result)
        	if result['success']:
	            username = form.cleaned_data.get('username')
	            password = form.cleaned_data.get('password')
	            user = authenticate(username=username, password=password)
	            if user is not None:
	                if user.is_active:
	                    login(request, user)
	                    return redirect('events:dashboard')
	            else:
	                return render(request,'events/login.html',{'form' : form,'user' : user})
	        else:
	        	messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = UserLoginForm
    context = { 'form' : form }
    return render(request,'events/login.html', context)

@login_required(login_url='/login')
def log_out(request):
    logout(request)
    return redirect('events:index')



def register(request):
    if request.user.is_authenticated:
        return redirect('events:dashboard')
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            print(result)

            if result['success']:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('events/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                    'token':account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(
                            mail_subject, message, to=[to_email]
                )
                email.send()
                return HttpResponse('Please confirm your email address to complete the registration')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = SignupForm()

    context = { 'form' : form }
    return render(request, 'events/register.html', context)

@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('events:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'events/change_password.html', {
        'form': form
    })


def activate(request, uidb64, token, 
backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, 
backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Thank you for your email confirmation. Now you have logged In')
        return redirect('events:dashboard')
    else:
        return HttpResponse('Activation link is invalid!')

@login_required(login_url='/login')
def dashboard(request):
    # username = request.user
    # event_list = Schedule.objects.all().exclude(username=username)
    # latest_event_list = event_list.order_by('id')
    # paginator = Paginator(latest_event_list,5)
    # page = request.GET.get('page')
    # events = paginator.get_page(page)
    # context = {
    #     'events':events,
    #     'latest_event_list':latest_event_list
    # }
    # return render(request, 'events/dashboard.html')
    username = request.user
    latest_event_list = Schedule.objects.exclude(username = username)

    context = {
        'latest_event_list': latest_event_list,
    }
    return render(request, 'events/dashboard.html',context)
@login_required(login_url='/login')
def attendance(request,title_id):
    username = request.user
    event = get_object_or_404(Schedule,pk=title_id)
    try:

        selected_event = Attending.objects.get(username=username,title=event.title)
        print(selected_event)

    except Attending.DoesNotExist:
        selected_event = None
        if NotAttending.objects.filter(username=username,title=event.title).exists():
            messages.error(request, 'You are already not attending this event!')
            return redirect('events:dashboard')
        else:
            create_event = Attending.objects.create(username=username,title=event.title)

    if selected_event == None:
        event.attending += 1
        print(event.attending)
        event.save()
        messages.success(request, 'You are attending this event!')
        return redirect('events:dashboard')
    else:
        messages.error(request, 'You are already attending this event!')
        return redirect('events:dashboard')

@login_required(login_url='/login')
def not_attending(request,title_id):
    username = request.user
    event = get_object_or_404(Schedule,pk=title_id)
    try:

        selected_event = NotAttending.objects.get(username=username,title=event.title)
        print(selected_event)

    except NotAttending.DoesNotExist:
        selected_event = None
        if Attending.objects.filter(username=username,title=event.title).exists():
            messages.error(request, 'You are already attending this event!')
            return redirect('events:dashboard')
        else:
            create_event = NotAttending.objects.create(username=username,title=event.title)

    if selected_event == None:
        event.not_attending += 1
        event.save()
        messages.success(request, 'Wish you came to the event!')
        return redirect('events:dashboard')
    else:
        messages.error(request, 'You are already not attending this event!')
        return redirect('events:dashboard')

@login_required(login_url='/login')
def my_events(request):
    username = request.user
    my_events = Attending.objects.filter(username=username)
    return render(request,'events/my_events.html', {'my_events':my_events})


@login_required(login_url='/login')
def list_of_attendees(request,title):
    username = request.user
    events = Attending.objects.filter(title=title)
    print(events)

    return render(request,'events/list_of_attendees.html',{'events':events})

@login_required(login_url='/login')
def event_list(request):
	username = request.user
	events_list = Schedule.objects.filter(username=username)
	context = {
		'events_list':events_list,
	}
	return render(request,'events/event_list.html', context)

@login_required(login_url='/login')
def create_event(request):
	if request.method == 'POST':
		form = EventForm(request.POST)
		if form.is_valid():
			username = request.user
			event = username.schedule_set.create(title=request.POST['title'],day=request.POST['day'],start_time=request.POST['start_time'],venue=request.POST['venue'],notes=request.POST['notes'])
			print(event)
			return redirect('events:event_list')

	else:
		form = EventForm()
	username = request.user
	events_list = Schedule.objects.filter(username=username)

events/templates/events/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'events:activate' uidb64=uid token=token %}
{% endautoescape %}

events/templates/events/change_password.html
{% extends 'events/dashboardlayout.html' %}
{% load bootstrap4 %}
{% block title %}Change Password{% endblock %}
{% block content %}
<br>
<div class="jumbotron">
<div class="container">
  <body style="background-color:#333;">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


  <h2>Change Password</h2>
  <br>
<form method="post">
	<div class="form-group">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Save changes</button>
  {% endbuttons %}
</div>
</form>
</div>
</div>
{% endblock %}

events/templates/events/create_event.html
{% load bootstrap4 %}
<div class="modal-dialog">
            <div class="modal-content">
                 <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Create a new Event</h4>
                </div>
                 <div class="modal-body">
                     <form method="POST" action ="{% url 'events:create_event' %}">
                             {% csrf_token %}
                             <table>
                             {% bootstrap_form form %}
                             </table>

                 <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>

                    </div>
                </div>
            </div>
        </div>

events/templates/events/dashboard.html
{% extends 'events/dashboardlayout.html' %}
{% load bootstrap4 %}
{% block title %}Dashboard{% endblock %}
{% load static %}

<style>
	.text-focus-in {
	-webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-5-9 23:4:24
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

</style>


{% block content %}
<div class="container">
  {% if user.is_authenticated %}
<h3 class="page-header" align="right"> Welcome {{ user.first_name }}!</h3>
{% else %}
<h3> You are not logged in </h3>
{% endif %}
  <div class="jumbotron">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  {% if latest_event_list %}
  <h2 class="display-4">Discover Events</h2>
  <br>
  

  <ol>
    {% for event in latest_event_list %}
    <li><h4>{{ event.title }}</h4></li>
    <ul><h5>Date:</h5> {{ event.day }}</ul>
    <ul><h5>Time:</h5> {{ event.start_time }}</ul>
    <ul><h5>Venue:</h5> {{ event.venue }}</ul>
    <ul><h5>Note:</h5> {{ event.notes }}</ul>
    <br>
    <form action="{% url 'events:attendance' event.id %}" method="post">
      {% csrf_token %}
          <input type="hidden" name="title_id" value="username" />
    <button type="submit" class="btn btn-success">Attending</button>
  </form>
  <br>
  <form action="{% url 'events:not_attending' event.id %}" method="post">
      {% csrf_token %}
          <input type="hidden" name="title_id" value="username" />
    <button type="submit" class="btn btn-danger">Not Attending</button>
  </form>
    <br><br>
    {% endfor %}
  </ol>
{% else %}
    <p>No Events.</p>
{% endif %}
</div>
</div>



{% endblock %}

events/templates/events/dashboardlayout.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}

<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script>
    $(document).ready(function(){
        $("#cbutton").click(function(){
            $("#basicModal").load("{% url 'events:create_event' %}");
            });
        });
    </script>
    
      <script src="{% static 'events/js/submitevent.js' %}" type="text/javascript"></script>
      
      <script>
  var csrf_token = '{{ csrf_token }}'
</script>
      <script>
    function editpollfunc(event_id){
        var url = "{% url 'events:edit_event' 1234 %}".replace(/1234/, event_id.toString());
        $("#pollModal").load(url);
    }
    </script>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet'>
        <style>
            .btn-primary {
                background: #4285f4;
                border: 1px solid #1266f1;
                color: #ffffff;
                font-family: 'Open Sans', sans-serif;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: 0.23px;
                padding: 12px 32px;
                text-align: center;
                text-decoration: none;
        </style>
        <title>
        {% block title %}
        CrudMe
        {% endblock %}
        </title>
    </head>
    <body>
        {% include 'events/includes/dashboardheader.html' %}
        <div class="container">
        {% block content %}
        {% endblock %}
    </body>
</html>

events/templates/events/edit_event.html
{% load bootstrap4 %}
<div class="modal-dialog">
        <div class="modal-content">
             <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Reminders</h4>
                </div>
             <div class="modal-body">
                 <form method="POST" action ="{% url 'events:edit_event' event.id %}" >
                     {% csrf_token %}
                     {% bootstrap_form form %}
                        <br>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Edit</button>
                        </form>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

events/templates/events/event_list.html
{% extends 'events/dashboardlayout.html' %}
{% load static %}

{% block content %}
<div id="maindiv">
  <h1 class="page-header">My Events</h1>
    <button id="cbutton" class="btn btn-primary" data-toggle="modal" data-target="#basicModal" >
      <span class="glyphicon glyphicon-plus"></span>
      Create Event
    </button>
    <div class="modal fade" id="basicModal" role="dialog">
      <div class="modal-content">
      </div>
    </div>
  <br><br>
  <div class="jumbotron">
  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Time</th>
        <th>Venue</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events_list %}
        <tr>
          <td>{{ event.title }}</td>
          <td>{{ event.day }}</td>
          <td>{{ event.start_time }}</td>
          <td>{{ event.venue }}</td>
          <td>{{ event.notes }}</td>
      <td>
      <button onclick="editpollfunc('{{event.id}}')"  id="pollbutton" class="btn btn-warning btn" data-toggle="modal" data-target="#pollModal">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
      <div class="modal fade" id="pollModal" role="dialog">
    </div>
    &nbsp;
    <a href = "{% url 'events:delete_event' event.id %}" onclick="return confirm('Are you sure you want to Delete?');" id="delpoll" class="btn btn-danger">Delete</a>
    </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-info">No Events</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
</div>
{% endblock %}

events/templates/events/index.html
{% extends 'events/layout.html' %}
{% block content %}
{% load static %}

<body style="background-color:#DCDCDC;">
	<style>
h1 {
    color: white;
    text-align: center;
}
p {
    color: white;
    text-align: center;
} 
.bg-1 { 
       background-color: #1abc9c; /* Green */
        color: #ffffff;
    }
    .bg-2 { 
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
.container-fluid {
    padding-top: 100px;
    padding-bottom: 250px;
}

.color-change-2x {
  -webkit-animation: color-change-2x 2s linear infinite alternate both;
          animation: color-change-2x 2s linear infinite alternate both;
          padding-top: 150px;
    padding-bottom: 150px;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-5-9 22:48:3
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-2x {
  0% {
    background: #19dcea;
  }
  100% {
    background: #b22cff;
  }
}
@keyframes color-change-2x {
  0% {
    background: #19dcea;
  }
  100% {
    background: #b22cff;
  }
}

.kenburns-top {
  -webkit-animation: kenburns-top 5s ease-out both;
          animation: kenburns-top 5s ease-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2018-5-9 22:58:38
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-top
 * ----------------------------------------
 */
@-webkit-keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}
@keyframes kenburns-top {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
    -webkit-transform-origin: top;
            transform-origin: top;
  }
}

</style>
<div class="color-change-2x bg-1 text-center">
        <h1 class="cover-heading">Welcome to CrudMe!</h1>
        <p class="lead">Simple way to create and share events.</p>
        <p class="lead">
          <a href="{% url 'events:register' %}" class="btn btn-info btn-lg">Start Now!</a>
        </p>
  </div>
  <div class="container-fluid bg-2 text-center">
  <h3 class="display-4">Already Signed Up?</h3>
  <br>
  <p class="lead">
          <a href="{% url 'events:login' %}" class="btn btn-success btn-lg">Click here!</a>
        </p>
</div>


{% endblock %}

events/templates/events/login.html
{% extends 'events/layout.html' %}
{% load bootstrap4 %}
  {% bootstrap_css %}

{% block title %}Login{% endblock %}
{% block content %}
<head>
  <script src="https://www.google.com/recaptcha/api.js"></script>
</head>
<body style="background-color:#333;">
<div class="container">
  <br><br>
<div class="jumbotron">

{% if user == None %}
{% bootstrap_alert content %}
{% bootstrap_alert "Your username and password didn't match." alert_type='error' %}
{% endif %}
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  <h2>Login</h2>
  <br>
  <form method="POST" action ="{% url 'events:login' %}" >
    <div class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
    <div class="card-footer text-muted text-left">
    <a href= "{% url 'events:password_reset' %}">Forgot your password?</a>
  </div>
    <br>
    <div class="g-recaptcha" data-sitekey="6Ld8E1cUAAAAAB4cNo2nDdgviRDvbcaPRPhfNyO1"></div>
    <br>
    </div>
  </form>
</div></div>
{% endblock %}

events/templates/events/my_events.html
{% extends 'events/dashboardlayout.html' %}
{% block title %}My Events{% endblock %}

{% block content %}

<div class="container">
	<h2 class="page-header">Scheduled Events</h2>
<div class="jumbotron">

{% if my_events %}

  <ol>
    {% for event in my_events %}
    <li><h4>Title: </h4><h5>{{ event.title }}</h5></li>
    <br>
    <a href="{% url 'events:attendees' event.title %}" class="btn btn-danger"> List of Attendees</a>
    {% endfor %}
  </ol>
{% else %}
    <p>No Events.</p>
{% endif %}
</div>
</div>
{% endblock %}

events/templates/events/register.html
{% extends 'events/layout.html' %}
{% load bootstrap4 %}
{% block title %}Signup{% endblock %}

{% block content %}
<head>
  <script src="https://www.google.com/recaptcha/api.js"></script>
</head>
<body style="background-color:#333;">
<div class="container">
	<br>
<div class="jumbotron">
  <h2>Sign up</h2>
  <br>
  <form method="POST">
    <div class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
<br>
    <div class="g-recaptcha" data-sitekey="6Ld8E1cUAAAAAB4cNo2nDdgviRDvbcaPRPhfNyO1"></div>
    <br>
    {% buttons %}
    <button type="submit" class="btn btn-primary">Sign up</button>
    {% endbuttons %}
    <div class="card-footer text-muted text-left">
            Already have an account? <a href="{% url 'events:login' %}">Log in</a>
          </div>
    </div>
  </form>
</div></div>
{% endblock %}